spring:
  # Config database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stag-demo-cicd-github-action.cdjbdfaazrz0.us-east-1.rds.amazonaws.com:3306/demo_cicd_github_action
    username: root
    password: tungtung

  # JPA/HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect