spring:
  # Config database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev-demo-cicd-github-action.cda2eocaa9nf.ap-southeast-1.rds.amazonaws.com:3306/dev_demo_cicd_github_action
    username: root
    password: tungtung
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}


  # JPA/HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect